-- Insert dữ liệu vào bảng User
INSERT INTO User (username, full_name, address, dob, gender, email, password, is_admin)
VALUES
("sealed_vessel", "Sealed Vessel", "The Abyss", "1990-03-15", "Non-binary", "sealed_vessel@gmail.com", "sealed_vessel1990", FALSE),
("hornet_sentinel", "Hornet Sentinel", "Greenpath", "1985-06-22", "Female", "hornet_sentinel@gmail.com", "hornet_sentinel1985", TRUE),
("dryya", "Dryya", "Deepnest", "1988-07-11", "Female", "dryya@gmail.com", "dryya1988", FALSE),
("isma", "Isma", "Isma's Grove", "1983-04-09", "Female", "isma@gmail.com", "isma1983", FALSE),
("grimm_king", "Grimm King", "Grimm Troupe", "1975-09-03", "Male", "grimm_king@gmail.com", "grimm_king1975", FALSE),
("radiance", "Radiance", "The White Palace", "1600-01-01", "Non-binary", "radiance@gmail.com", "radiance1600", FALSE),
("quirrel", "Quirrel", "Forgotten Crossroads", "1987-05-22", "Male", "quirrel@gmail.com", "quirrel1987", FALSE),
("cornifer", "Cornifer", "Forgotten Crossroads", "1991-03-30", "Male", "cornifer@gmail.com", "cornifer1991", FALSE),
("clayton", "Clayton", "Distant Village", "1989-11-10", "Male", "clayton@gmail.com", "clayton1989", FALSE),
("lady_of_the_nail", "Lady of the Nail", "The Abyss", "1978-10-20", "Female", "lady_of_the_nail@gmail.com", "lady_of_the_nail1978", FALSE),
("mossking", "Moss King", "The Mossy Grotto", "1984-02-18", "Male", "mossking@gmail.com", "mossking1984", FALSE),
("pale_king", "Pale King", "The White Palace", "1500-01-01", "Male", "pale_king@gmail.com", "pale_king1500", FALSE),
("dreamer", "Dreamer", "The Dream Realm", "1550-12-25", "Non-binary", "dreamer@gmail.com", "dreamer1550", FALSE),
("mantis_lord", "Mantis Lord", "Mantis Village", "1981-12-12", "Male", "mantis_lord@gmail.com", "mantis_lord1981", FALSE),
("monomon", "Monomon the Teacher", "The Teacher's Archives", "1350-06-14", "Female", "monomon@gmail.com", "monomon1350", FALSE),
("lurien", "Lurien the Watcher", "The Watcher's Spire", "1400-09-21", "Male", "lurien@gmail.com", "lurien1400", FALSE),
("herrah", "Herrah the Beast", "The Beast's Den", "1450-02-11", "Female", "herrah@gmail.com", "herrah1450", FALSE),
("pure_vessel", "Pure Vessel", "The Abyss", "2020-04-10", "Non-binary", "pure_vessel@gmail.com", "pure_vessel2020", FALSE),
("broken_vessel", "Broken Vessel", "The Abyss", "2022-07-15", "Male", "broken_vessel@gmail.com", "broken_vessel2022", FALSE),
("hollow_knight", "Hollow Knight", "The Black Egg Temple", "2024-09-01", "Male", "hollow_knight@gmail.com", "hollow_knight2024", FALSE),
("white_lady", "White Lady", "The White Palace", "1505-06-10", "Female", "white_lady@gmail.com", "white_lady1505", FALSE),
("the_grub", "The Grub", "The Grubfather's Home", "1998-07-22", "Male", "the_grub@gmail.com", "the_grub1998", FALSE),
("vessel", "Vessel", "The Abyss", "2001-01-15", "Non-binary", "vessel@gmail.com", "vessel2001", FALSE),
("god_tamer", "God Tamer", "Colosseum of Fools", "1999-10-12", "Female", "god_tamer@gmail.com", "god_tamer1999", FALSE),
("millibelle", "Millibelle the Banker", "The City of Tears", "1992-06-10", "Female", "millibelle@gmail.com", "millibelle1992", FALSE),
("uomo", "Uomo", "Dirtmouth", "1987-11-13", "Male", "uomo@gmail.com", "uomo1987", FALSE),
("zote", "Zote the Mighty", "Forgotten Crossroads", "1990-04-20", "Male", "zote@gmail.com", "zote1990", FALSE),
("voidheart", "Voidheart", "The Abyss", "2020-12-01", "Non-binary", "voidheart@gmail.com", "voidheart2020", FALSE),
("fungus", "Fungus", "Fungal Wastes", "1989-05-22", "Male", "fungus@gmail.com", "fungus1989", FALSE),
("nailmaster_oro", "Nailmaster Oro", "The Nailmasters' Retreat", "1980-08-30", "Male", "nailmaster_oro@gmail.com", "nailmaster_oro1980", FALSE),
("nailmaster_mato", "Nailmaster Mato", "The Nailmasters' Retreat", "1984-12-01", "Male", "nailmaster_mato@gmail.com", "nailmaster_mato1984", FALSE),
("cornifer_wife", "Cornifer's Wife", "Forgotten Crossroads", "1992-01-18", "Female", "cornifer_wife@gmail.com", "cornifer_wife1992", FALSE),
("tollkeeper", "Tollkeeper", "Kingdom's Edge", "1991-09-05", "Male", "tollkeeper@gmail.com", "tollkeeper1991", FALSE),
("grubfather", "Grubfather", "The Grubfather's Home", "1977-11-25", "Male", "grubfather@gmail.com", "grubfather1977", FALSE),
("elderbug", "Elderbug", "Dirtmouth", "1955-05-23", "Male", "elderbug@gmail.com", "elderbug1955", FALSE),
("traitorlord", "Traitor Lord", "The Abyss", "1981-03-18", "Male", "traitorlord@gmail.com", "traitorlord1981", FALSE),
("mantis", "Mantis", "Mantis Village", "1993-02-11", "Female", "mantis@gmail.com", "mantis1993", FALSE),
("grub", "Grub", "The Forgotten Paths", "2002-07-25", "Male", "grub@gmail.com", "grub2002", FALSE),
("gatherer", "Gatherer", "Fungal Wastes", "1982-04-01", "Female", "gatherer@gmail.com", "gatherer1982", FALSE),
("weaver", "Weaver", "Weaver's Den", "1995-03-22", "Male", "weaver@gmail.com", "weaver1995", FALSE);